repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - assets/nf-core-genephylomodeler_logo_light.png
    - docs/images/nf-core-genephylomodeler_logo_light.png
    - docs/images/nf-core-genephylomodeler_logo_dark.png

template:
  org: nf-core
  name: genephylomodeler
  description: Selection analysis using phylogenetics
  author: Nina Xiong
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
