lint:
  files_unchanged:
    - assets/nf-core-genephylomodeler_logo_light.png
    - docs/images/nf-core-genephylomodeler_logo_light.png
    - docs/images/nf-core-genephylomodeler_logo_dark.png
    - .gitignore
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Nina Xiong
  description: Selection analysis using phylogenetics
  force: false
  is_nfcore: true
  name: genephylomodeler
  org: nf-core
  outdir: .
  version: 1.0.0dev
